### PR TITLE
fix: Fix `winget.yml` run workspace and fix `build.ps` can't install `wingetcreate`

### PR DESCRIPTION
**Pull request by SinnoSong**
Fix `winget.yml` run workspace and fix `build.ps` can't install `wingetcreate`

### CODE REVIEW

**Comment by SinnoSong** [comment]
@zurawiki I see your winget.yml work not success,I fix the run workspcea error, and fix build.ps1 can not import AppX.

**Comment by SinnoSong** [comment]
image
Here is github action debug log. It can be submit pull request.

**Comment by zurawiki** [comment]
Ran the action at https://github.com/zurawiki/gptcommit/actions/runs/4629758277

**Comment by SinnoSong** [comment]
@zurawiki Do you create a `personal access token`? Please lock at https://github.com/orgs/community/discussions/24770

**Pull request merged**
